name: Copy with azcopy

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "develop"
jobs:
  copy_manual_files:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Upload file
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      run: |
        export AZCOPY_TENANT_ID=$(echo $AZURE_CREDENTIALS | jq -r '.["tenantId"]')
        export AZCOPY_AUTO_LOGIN_TYPE=SPN
        export AZCOPY_SPA_APPLICATION_ID=$(echo $AZURE_CREDENTIALS | jq -r '.["clientId"]')
        export AZCOPY_SPA_CLIENT_SECRET=$(echo $AZURE_CREDENTIALS | jq -r '.["clientSecret"]')
        echo "::add-mask::$AZCOPY_SPA_APPLICATION_ID"
        echo "::add-mask::$AZCOPY_SPA_CLIENT_SECRET"
        azcopy copy .github "https://mlopsstarter.blob.core.windows.net/democontainer" --recursive
