name: Copy with azcopy

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "develop"
jobs:
  copy_manual_files:
    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
